Repository taba7-algorivew/front, pull requests merged in 2025-02, with the labels that each got.

#46 Fix : 모든 타입오류 해결
  src/App.tsx
  src/api/BaseApi.tsx
  src/components/CustomSidebar.tsx
  src/components/HighLight.tsx
  src/components/History.tsx
  src/pages/ReviewPage.tsx
Labels: documentation

#50 사이드바 버그 수정
  src/pages/ReviewPage.tsx
Labels: documentation

#52 모범답안 출력 에러 수정
  src/components/Feedback.tsx
  src/components/SolutionCode.tsx
Labels: bug, must Fix

#53 Fix: solutioncode.tsx에 대한 타입 에러 수정 및 수정으로 인한 오류 없음 확인
  src/api/BaseApi.tsx
  src/components/SolutionCode.tsx
Labels: bug

#55 Add : homepage 기본 틀 제작. +이미지 파일을 넣을 assets/image폴더 생성
  src/assets/images/main_page.png
  src/layouts/HomeLayout.tsx
  src/pages/HomePage.tsx
  src/styles/homepage.css
Labels: documentation

#57 Fix: homepage 섹션 로직 분리
  src/pages/HomePage.tsx
  src/styles/homepage.css
Labels: documentation

#59 Add : 홈페이지 인트로 스타일 추가 + homepage_Intro.css, CustomEditor.tsx파일 추가
  .dockerignore
  src/api/BaseApi.tsx
  src/components/CustomEditor.tsx
  src/pages/HomePage.tsx
  src/styles/homepage.css
  src/styles/homepage_Intro.css
Labels: documentation

#63 Refactor: Change api baseURL. swagger -> web_domain
  src/api/BaseApi.tsx
Labels: must Fix

#66 FINISH : 프론트 최종 작업 - 주석처리 삭제 및 가독성 향상
  src/api/BaseApi.tsx
  src/api/ChatbotApi.tsx
  src/api/FeedbackApi.tsx
  src/api/HistoriesApi.tsx
  src/api/LoginApi.tsx
  src/api/ReviewRequestApi.tsx
  src/api/SolutionApi.tsx
  src/components/Chatbot.tsx
  src/components/CodeEditor.tsx
  src/components/CompleteDialog.tsx
  src/components/CustomEditor.tsx
  src/components/Feedback.tsx
  src/components/Header.tsx
  src/components/HighLight.tsx
  src/components/LoadingLogo.tsx
  src/components/SolutionCode.tsx
  src/components/UrlOrFileUploader.tsx
  src/layouts/HomeLayout.tsx
  src/pages/HomePage.tsx
  src/pages/LoginPage.tsx
  src/pages/RegisterPage.tsx
  src/pages/ReviewPage.tsx
  src/pages/TutorialPage.tsx
  src/styles/homepage.css
  src/styles/homepage_Intro.css
  src/styles/tutorial.css
Labels: good first issue
